# -*- coding: utf-8 -*-
"""Timecomplexity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13eMztYZyhHJbL_QSbqhDJS5-6eE8O0OU

1. # Measuring Time
"""

import time                     # Problems wih this approach - (counting time)
                                  # diffrent time for different algorithm
start = time.time()                # time varies if implementation changes
for i in range(1,101):              # diffrent machines different time
  print(i)                            # does not work for extremely small input
end = time.time()                       # time varies for different inputs, but
print(end - start)                        # -can't establish a relationship

#2nd implementation of same problem
start = time.time()
i = 0
while i != 100:
  print(i)
  i += 1
end = time.time()
print(end - start)

"""2. # Measuring Operations"""

def c_to_f(c):
  return c*9.0/5 + 32 # (no of ops - 3)  time varies if implementation changes
                  # no clear definition of which operation to count

"""#What do we want:
1. We want to evaluate the algorithm
2. We want to evaluate scalablity
3. We want to evaluate in terms of input size

#Three Cases in Time Complexity:
- Best Case
- Worst Case
- Average Case
"""

def search_for_elmt(L, e):
    return e in L
# when e is the first element in the list - Best Case
# when e is the last element in the list - Worst Case
# when look through about half of elements - Avg Case

"""# ORDERS OF GROWTH
Goals:
- want to evaluate program's efficiency when input is very big
- want to express the growth of program's run time as input size grows
- want to put an upper bound on growth - as tight as possible
- do not need to be precise : "order of" not "exact" growth
- we will look at largest factors in run time (which section of the program will take the longest to run?)
- thus , generally we want tight upper bound on growth , as function of size of input, in worst case

"""

# factorial compute
def fact_iter(n):
  answer = 1  #1 operation
  while n >1:   #  Inside +1 op everytime condition checks
    answer *= n # 2 operations ( multiply and assign)
    n -= 1 # 2 operations ( subtract and assign)
  return answer # 1 operation
    # loop runs n-1 times with 5 ops every time = 5(n-1)
  # Total no of operations =1 + 5(n-1) + 1 + 1 = 5n - 2
  # But we ignore all constants and all multiplicative constants as well
  # So the time Complexity will be (O)N

"""````````
n² + 2n+ 2 - N² will be the time complexity
``````````

```
n² + 100000n + 3¹⁰⁰⁰ - N² will be the time complexity
````

```
log(n) + n + 4 - (O)n
```

```
0.0001 * n * log(n)+ 300n - n(logn)
```

```
2n³⁰ + 3ⁿ - 3ⁿ
```
"""

import matplotlib.pyplot as plt

"""#Types of ORDERS OF GROWTH

#Constant Time Complexity - A function has **constant time complexity** if it takes same amount of time reagrdless of input size.
- It does not depend on n
- Time stays fixed
- Graph is a horizontal line
- Notation is O(1)
"""

n = list(range(1, 11))

# Constant time (e.g., always 5 operations)
time = [5 for _ in n]

plt.plot(n, time)
plt.xlabel('Input size (n)')
plt.ylabel('Time (operations)')
plt.title('Constant Time Complexity O(1)')
plt.show()

"""# Linear Time Complexity - A function has **linear time complexity** if its running time increases  directly proportional to  size of the input (n).
- If n doubles --> time also doubles
- Graph is a slanted line.
- Notation is O(n).

Ex - Traversing through an array
"""

import numpy as np
n = np.arange(0, 100, 1)

T = n

plt.plot(n, T)
plt.xlabel("Input Size (n)")
plt.ylabel("Time Taken T(n)")
plt.title("Linear Time Complexity O(n)")

plt.grid()

plt.show()

"""#Quadratic Time Complexity - A function has **quadratic time complexity** when its running time grows proportional to the square of the input size.
- If n doubles --> time becomes 4 times, If n triples --> time becomes 9 times
- Graph = curved (parabolic) ,gets steep quick
- Notation is O(n)².

Ex- Nested loops
"""

#  Quadratic Time complexity
n = np.arange(0,50,1)
T = n**2
plt.plot(n,T)
plt.xlabel("Input Size (n)")
plt.ylabel("Time Taken T(n)")
plt.title("Quadratic Time Complexity O(n²)")
plt.grid()
plt.show()

"""#Logarithmic Time Complexity - A function has **logarithmic time complexity** where running time grows increases very slowly as the input size grows.
- If input doubles --> runtime increases ny only a small constant.
- Graph grows rapidly at start and flattens out quickly.  
-  Notation is O(log n).

Ex - Binary Search

"""

n = np.linspace(1,100,100)
log_n = np.log2(n)

plt.figure()
plt.plot(n,log_n)
plt.xlabel("Input Size (n)")
plt.ylabel("Time Taken T(n)")
plt.title("Logarithmic Time Complexity O(log n)")
plt.grid()
plt.show()

"""#Linearithmic Time Complexity - A function has linear time complexity whose running time grows proportionally to n log n ( a combination of linear growth and logarithmic growth.)
- Slower than O(n) and Faster than O(n²) efficient for large datasets
- Notation is O(n log n)[linear * logarithmic growth]
- Graph rises rapidly at start, then flattens quickly

Ez - Merge Sort, Quick Sort,Heap Sort
"""

# Linearithmic Time Complexity
n = np.linspace(1,100,500)
linearithmic = n * np.log2(n)

plt.plot(n , linearithmic,linewidth =2)
plt.xlabel("Input Size (n)")
plt.ylabel("Time Taken T(n)")
plt.title("Linearithmic Time Complexity O(n log n)")
plt.grid(alpha=0.3)
plt.show()

"""# Exponential Time Complexity - A function has **exponential time complexity** when the running time grows proportionally to an exponential function of the input size.
- Very slow for large inputs and not practical for large datasets
- Doubles (or  worse) with each increment in input
- Starts off slow , then shoots up dramatically and becomes almost vertical
- Notation is O(2ⁿ)

Ex - used in brute force recursion
"""

# Exponential time complexity
n = np.linspace(1,10,100)
exponential = 2**n

plt.plot(n,exponential)
plt.xlabel("Input Size (n)")
plt.ylabel("Time Taken T(n)")
plt.title("Exponential Time Complexity")
plt.grid(alpha=0.3)
plt.show()

"""# Law of Addition
 Law of Addition for O():
 - used with sequential statements
 - O(f(n)) + O (g(n)) is o( f(n) + g(n) )

 Ex :
 ```
 for i in range(n):      
   print('a')            
 for j in range(n*n):    
   print('b')            
 ```
is O(n) + o(n*n) = O( n + n²) because of dominant term

# Law of Multiplication

Law of Multipliication for O():
- used with nested statements /loops
- O(f(n)) * O (g(n)) is O( f(n) * g(n) )

Ex :
````
for i in range(n):
    for j in range(n):
        print('a')
````
is O(n) * O(n) = O (n*n) = O(n²) because the outer loop goes n times and the inner loop goes n times for every outer loop iter.
"""

from decorator import DEF
import pandas as pd
import numpy as np
n_values = [10,100,1000,1000000]
data ={
    "n" : n_values,
    "O(1)" : [1 for n in n_values],
    "O(log n)" : [np.log2(n) for n in n_values],
    "O(n)" : [n for n in n_values],
    "O(n log n)" : [n * np.log2(n) for n in n_values],
    "O(n²)" : [n**2 for n in n_values],
    "o(2 ⁿ)" : [2**n if n <= 30 else "Too large" for n in n_values]
}
df = pd.DataFrame(data, index=n_values).T
df.columns.name = "Input (n)"
df.index.name = "Complexity"
pd.set_option('display.float_format', '{:.2f}'.format)
df
df

#  o(log n) -Logarithmic time complexity
number =  int(input('enter the number: '))

digits = '0123456789'
result = ''
while number != 0:
  result = digits[number % 10] + result
  number = number // 10
print(result)

# O(n) - linear time complexity
L = [1,2,3,4]
sum = 0
for i in L:
  sum += i
product = 1
for i in L:
  product *= i
print(sum, product)

# O(n²) - Quadratic Time Complexity
A = [1,2,3,4]
B = [5,6,7,8]
for i in A:
  for j in B:
    print(i,j)

# O(n²) - Quadratic Time Complexity
A = [1,2,3,4]
B = [5,6,7,8]

for i in A:
  for j in B:
    for k in range(1000000):
      print(i,j)

# O(n) - Linear time complexity
L = [1,2,3,4,5]

for i in range(0,len(L)//2):
  other = len(L) - i - 1
  temp = L[i]
  L[i] = L[other]
  L[other] = temp
print(L)

# O(n log n)- Linearithmic Time Complexity
n = 10
k = 0
for i in range(n//2,n):
  for j in range(2,n ,pow(2,j)):
    k += n/2
print(k)

# O(n)- Constant time complexity
a = 10
b = 3

if b <= 0:
  print(-1)
div = a//b
print(a-div-b)

# O( log n) - Logarithmic time complexity
n = 3456
sum = 0
while n>0:
  sum += n%10
  n //= 10
print(sum)

# O(2ⁿ) Exponential time complexity
def fib(n):
  if n== 1 or n ==0:
    return 1
  else:
    return fib(n-1) + fib(n-2)
fib(5)